CREATE TABLE IF NOT EXISTS TUTORIAL (
    ID NUMBER NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    PUBLISHED BOOLEAN NOT NULL DEFAULT(FALSE),
    PRIMARY KEY (ID)
);